# Generated by Django 5.0.6 on 2025-12-04 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("telegram_id", models.TextField(unique=True)),
                ("username", models.TextField(blank=True, null=True)),
                ("first_name", models.TextField(blank=True, null=True)),
                ("last_name", models.TextField(blank=True, null=True)),
                ("phone", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="SystemSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("theme", models.TextField(default="default")),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Tournament",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                ("date", models.DateTimeField()),
                ("type", models.TextField()),
                (
                    "status",
                    models.TextField(
                        choices=[
                            ("SCHEDULED", "Scheduled"),
                            ("RUNNING", "Running"),
                            ("PAUSED", "Paused"),
                            ("FINISHED", "Finished"),
                            ("BREAK", "Break"),
                        ],
                        default="SCHEDULED",
                    ),
                ),
                ("break_start_time", models.DateTimeField(blank=True, null=True)),
                ("break_duration_minutes", models.IntegerField(blank=True, null=True)),
                ("season", models.TextField(blank=True, null=True)),
                ("buy_in", models.IntegerField(blank=True, null=True)),
                ("stack", models.IntegerField(default=10000)),
                ("config", models.TextField(default="{}")),
                ("current_level_index", models.IntegerField(default=0)),
                ("level_started_at", models.DateTimeField(blank=True, null=True)),
                ("timer_paused_at", models.DateTimeField(blank=True, null=True)),
                ("timer_seconds", models.IntegerField(blank=True, null=True)),
                ("registration_closed", models.BooleanField(default=False)),
                ("display_settings", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="TournamentTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                ("description", models.TextField(blank=True, null=True)),
                ("type", models.TextField()),
                ("buy_in", models.IntegerField(blank=True, null=True)),
                ("stack", models.IntegerField(default=10000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("table_number", models.IntegerField()),
                ("max_seats", models.IntegerField(default=9)),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tables",
                        to="core.tournament",
                    ),
                ),
            ],
            options={
                "ordering": ["table_number"],
            },
        ),
        migrations.CreateModel(
            name="Payout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.IntegerField()),
                ("place", models.IntegerField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "player",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.player",
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payouts",
                        to="core.tournament",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GameEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.TextField()),
                ("description", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="core.tournament",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TournamentLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level_number", models.IntegerField()),
                ("small_blind", models.IntegerField()),
                ("big_blind", models.IntegerField()),
                ("ante", models.IntegerField(default=0)),
                ("duration", models.IntegerField()),
                ("is_break", models.BooleanField(default=False)),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="levels",
                        to="core.tournament",
                    ),
                ),
            ],
            options={
                "ordering": ["level_number"],
            },
        ),
        migrations.CreateModel(
            name="TemplateLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level_number", models.IntegerField()),
                ("small_blind", models.IntegerField()),
                ("big_blind", models.IntegerField()),
                ("ante", models.IntegerField(default=0)),
                ("duration", models.IntegerField()),
                ("is_break", models.BooleanField(default=False)),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="levels",
                        to="core.tournamenttemplate",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Registration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.TextField(
                        choices=[
                            ("REGISTERED", "Registered"),
                            ("ELIMINATED", "Eliminated"),
                        ],
                        default="REGISTERED",
                    ),
                ),
                ("rebuys", models.IntegerField(default=0)),
                ("addons", models.IntegerField(default=0)),
                ("place", models.IntegerField(blank=True, null=True)),
                ("bounty_count", models.IntegerField(default=0)),
                ("points", models.IntegerField(blank=True, null=True)),
                ("seat_number", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registrations",
                        to="core.player",
                    ),
                ),
                (
                    "table",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="registrations",
                        to="core.table",
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registrations",
                        to="core.tournament",
                    ),
                ),
            ],
            options={
                "unique_together": {("player", "tournament")},
            },
        ),
    ]
