# Generated by Django 5.0.6 on 2025-12-05 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="is_admin",
            field=models.BooleanField(default=False),
        ),
    ]
